export const finderData = [
  {
    name: "Finder",
    options: [
      { content: "Finder에 관하여" },
      { border: true },
      { content: "설정" },
      { border: true },
      { content: "휴지통 비우기..." },
      { border: true },
      { content: "서비스" },
      { border: true },
      { content: "Finder 가리기" },
      { content: "기타 가리기" },
      { content: "모두 보기" },
    ],
  },
  {
    name: "파일",
    options: [
      { content: "새로운 Finder 윈도우" },
      { content: "새로운 폴더" },
      { content: "선택 항목을 포함하는 새로운 폴더" },
      { content: "새로운 스마트 폴더" },
      { content: "새로운 탭" },
      { content: "열기" },
      { content: "다음으로 열기" },
      { border: true },
      { content: "정보 가져오기" },
      { content: "이름 변경" },
      { content: "압축" },
      { content: "복제" },
      { content: "가상본 만들기" },
      { content: "훑어보기" },
      { content: "프린트" },
      { border: true },
      { content: "공유..." },
      { border: true },
      { content: "원본 보기" },
      { content: "Dock에 추가" },
      { border: true },
      { content: "휴지통으로 이동" },
      { content: "추출" },
      { content: "태그..." },
      { content: "추출" },
    ],
  },
  {
    name: "편집",
    options: [
      { content: "변경 실행 취소" },
      { content: "실행 복귀" },
      { border: true },
      { content: "오려두기" },
      { content: "복사" },
      { content: "붙여넣기" },
      { content: "전체 선택" },
      { border: true },
      { content: "클립보드 보기" },
      { border: true },
      { content: "받아쓰기 시작..." },
      { content: "이모티콘 및 기호" },
    ],
  },
  {
    name: "보기",
    options: [
      { content: "아이콘" },
      { content: "목록" },
      { content: "계층" },
      { content: "갤러리" },
      { border: true },
      { content: "스택 사용" },
      { content: "다음으로 스택 그룹화" },
      { content: "아이콘 정리" },
      { content: "아이콘 정리 방식" },
      { border: true },
      { content: "사이드바 가리기" },
      { content: "미리보기 가리기" },
      { border: true },
      { content: "도구 막대 가리기" },
      { content: "모든 탭 보기" },
      { content: "탭 막대 가리기" },
      { content: "경로 막대 가리기" },
      { content: "상태 막대 가리기" },
      { border: true },
      { content: "도구 막대 사용자화..." },
      { border: true },
      { content: "보기 옵션" },
      { content: "보겨 옵션 표시" },
      { border: true },
      { content: "전체 화면 시작" },
    ],
  },
  {
    name: "이동",
    options: [
      { content: "뒤로" },
      { content: "앞으로" },
      { content: "시동 디스크 선택하기" },
      { border: true },
      { content: "최근 사용" },
      { content: "문서" },
      { content: "데스크탑" },
      { content: "다운로드" },
      { content: "홈" },
      { content: "컴퓨터" },
      { content: "AirDrop" },
      { content: "네트워크" },
      { content: "iCloud Drive" },
      { content: "공유" },
      { content: "응용 프로그램" },
      { content: "유틸리티" },
      { border: true },
      { content: "최근 사용 폴더" },
      { border: true },
      { content: "폴더로 이동..." },
      { content: "서버에 연결..." },
    ],
  },
  {
    name: "윈도우",
    options: [
      { content: "최소화" },
      { content: "확대/축소" },
      { content: "화면 왼쪽으로 윈도우 이동" },
      { content: "화면 오른쪽으로 윈도우 이동" },
      { content: "배치된 윈도우 대치" },
      { border: true },
      { content: "세트에서 윈도우 제거" },
      { content: "윈도우 순환" },
      { content: "진행 윈도우 보기" },
      { border: true },
      { content: "이전 탭 보기" },
      { content: "다음 탭 보기" },
      { content: "새로운 윈도우로 탭 이동" },
      { content: "모든 윈도우 통합" },
      { border: true },
      { content: "모두 앞으로 가져오기" },
    ],
  },
  {
    name: "도움말",
    options: [
      { content: "검색" },
      { content: "Mac을 위한 팁" },
      { content: "macOS 도움말" },
    ],
  },
];
